# Pytorch Basic 1：张量（Tensor）

In [1]:
## load packages
import torch
import numpy as np

## 看一下torch 版本
print(torch.__version__)

1.10.0+cu111


## 张量(Tensor)
张量的英文是Tensor，它是PyTorch里面基础的运算单位，与Numpy的ndarray相同都表示的是一个多维的矩阵。

与ndarray的最大区别就是，PyTorch的Tensor可以在``GPU``上运行，而 numpy 的 ndarray 只能在 CPU 上运行，在GPU上运行大大加快了运算速度。



### 创建Tensor

In [2]:
x=torch.rand(2,3) ## 生成一个2*3的tensor
y=torch.rand(2,3,4,5) ## 生成一个2*3*4*5的多维tensor

#### 其他初始化方法

In [ ]:
zero=torch.zeros(2,2) ## 2*2 tensor，元素全为0
ones=torch.ones(2,2) ## 2*2 tensor,元素全为1
eye=torch.eye(2,2) ## 2*2 tensor,单位矩阵
rand=torch.rand(2,2) ## 2*2 tensor，元素大小随机

###查看Tensor的维度

In [5]:
print(x.size()) ## 通过 .size()方法查看维度
print(np.shape(y)) ## 通过np.shape()函数来查看

torch.Size([2, 3])
torch.Size([2, 3, 4, 5])


在同构的意义下:

第零阶张量 （r = 0） 为标量 （Scalar）

第一阶张量 （r = 1） 为向量 （Vector）

第二阶张量 （r = 2） 则成为矩阵 （Matrix）

第三阶以上的统称为多维张量。

其中要特别注意的就是标量，我们先生成一个标量：


In [4]:
scalar=torch.tensor(1.433223) ## 直接用一个已有的数据生成tensor
print(scalar)


print(scalar.item()) ## 用 .item()方法查看一个标量对应的python对象数值
print(type(scalar.item()),'\n') ## <class 'float'> 

tensor = torch.tensor([3.1433223]) ## 特别的,如果张量中只有一个元素的tensor也可以调用`tensor.item`方法
print(tensor)
print(tensor.item())

tensor(1.4332)
1.433223009109497
<class 'float'> 

tensor([3.1433])
3.143322229385376


###基本类型
Tensor的基本数据类型有五种：
- 32位浮点型：torch.FloatTensor。 (默认)
- 64位整型：torch.LongTensor。
- 32位整型：torch.IntTensor。
- 16位整型：torch.ShortTensor。
- 64位浮点型：torch.DoubleTensor。

除以上数字类型外，还有byte和chart型

## Tensor和Numpy的转换
使用numpy方法将Tensor转为ndarray

In [7]:
a_tensor=torch.randn(3,2)
print(a_tensor)
a_numpy=a_tensor.numpy() ## 将tensor转化为numpy
print(a_numpy)

tensor([[ 0.0920,  1.1896],
        [-1.5687, -1.0908],
        [-0.0830, -0.5482]])
[[ 0.09199096  1.1895736 ]
 [-1.5686744  -1.0907832 ]
 [-0.08302718 -0.5481665 ]]


In [8]:
tensor_a=torch.tensor(a_numpy) ## 将numpy转化成tensor
tensor_a=torch.from_numpy(a_numpy) ## 效果一样
print(tensor_a) 

tensor([[ 0.0920,  1.1896],
        [-1.5687, -1.0908],
        [-0.0830, -0.5482]])


Tensor和numpy对象***共享内存***，所以他们之间的转换很快，而且几乎不会消耗什么资源。但这也意味着，如果***其中一个变了，另外一个也会随之改变***。（具体查看60 minutes）

## 设备间转换
一般情况下可以使用.cuda方法将tensor移动到gpu，这步操作需要cuda设备支持

In [ ]:
print(torch.cuda.is_available()) ## 查看cuda是否可用

cpu_a=torch.rand(4, 3)
cpu_a.type()

gpu_a=cpu_a.cuda() ## 用 .cuda()方法把tensor移到GPU中
gpu_a.type()

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
gpu_a=cpu_a.to(device) ## 和 .cuda()方法一样，不过更推荐这种用法，可以在多GPU情况下指定GPU
gpu_a.type()

## 常用方法
PyTorch中对张量的操作api 和 NumPy 非常相似，如果熟悉 NumPy 中的操作，那么他们二者基本是一致的：

In [ ]:
x=torch.rand(5,3)
y=torch.rand(5,3)

print(x,'\n',y)

## 和，差
print(x+y,end='\n') ## 同torch.add(x,y,out=result)，即把x+y结果赋值给result
print(x-y,end='\n')

## 加+替换
print(y,'\n')
y.add_(x)
print(y,'\n') ## 这里的y是上面的y+x的结果

## 内积(点乘)
u=torch.rand(3,2) 
v=torch.rand(3,2)
print(u.mul(v)) ## 返回仍然是3*2矩阵

## 外积（叉乘）
v1=torch.rand(2,3)
print(u.mm(v1)) ## 返回3*3矩阵

## view改变tensor维度
x=torch.rand(5,3)
print(x)
y=x.view(15)
print(np.shape(y))
z=x.view(3,5)
print(z) ## 这里和转置不一样，是近似于先把原来的tensor转化成一个list，然后再重新按照行列要求生成一个tensor

print(x.view(-1,15)) ## 这里的-1是我们不想算有几行，让电脑帮我们算

## 沿着行取最大值
max_value, max_idx = torch.max(x, dim=1)
print(max_value, max_idx)

## 对行求和
sum_x = torch.sum(x, dim=1)
print(sum_x)